services:
  - type: web
    name: line-chatgpt-booking
    env: python
    buildCommand: ""
    startCommand: python main.py
    plan: free
    envVars:
      - key: LINE_CHANNEL_SECRET
        value: your-line-secret
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: your-line-token
      - key: OPENAI_API_KEY
        value: your-openai-api-key
    ports:
      - 10000
